import type { FoodEntry } from "../models/foodEntryInterface";

export const menusEntries: FoodEntry[] = [
	{
		title: "Plateau Original",
		piecesNumber: 12,
		image: "/plateau_original.png",
		price: 13.90,
		elements: [
			"6 californias saumon avocat",
			"3 sushis saumon",
			"3 sashimis saumon",
			"Edamame",
			"Salade de chou"      
		],
	},
	{
		title: "Plateau Maki",
		piecesNumber: 18,
		image: "/plateau_maki.png",
		price: 13.90,
		elements: [
			"6 makis saumon",
			"6 makis thon",
			"6 makis avocat cheese",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Végétarien",
		piecesNumber: 15,
		image: "/plateau_vege.png",
		price: 13.50,
		elements: [
			"6 californias végétariens",
			"3 springs avocat cheese",
			"6 springs concombre cheese",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Sushi Saumon",
		piecesNumber: 10,
		image: "/plateau_sushi.png",
		price: 15.95,
		elements: [
			"10 sushis saumon",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Sushi Mix",
		piecesNumber: 10,
		image: "/plateau_sushi_mix.png",
		price: 17.5,
		elements: [
			"5 sushis saumon",
			"5 sushis thon",
			"Edamame", 
			"Salade de chou",
		],
	},
	{
		title: "Sushi Lovers",
		piecesNumber: 18,
		image: "/plateau_sushi_lovers.png",
		price: 17.9,
		elements: [
			"6 californias saumon avocat",
			"6 springs saumon avocat",
			"6 sushis saumon",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Sushi Assortiment",
		piecesNumber: 10,
		image: "/plateau_sushi_assortiment.png",
		price: 19.5,
		elements: [
			"2 sushis saumon",
			"2 sushis thon",
			"2 sushis crevette",
			"2 sushis daurade",
			"2 sushis ikura",
			"Edamame",
			"Salade de chou",
		],
	},
  	{
		title: "Plateau California",
		piecesNumber: 18,
		image: "/plateau_california.png",
		price: 16.95,
		elements: [
			"3 californias saumon avocat",
			"6 californias thon avocat",
			"3 californias thon cuit avocat",
			"3 californias végétariens",
			"3 californias saumon cheese avocat",
			"Edamame",
			"Salade de chou",
		],
	},
 	{
		title: "Plateau Spring",
		piecesNumber: 18,
		image: "/plateau_spring.png",
		price: 17.5,
		elements: [
			"3 springs saumon avocat",
			"3 springs thon avocat",
			"6 springs thon cuit avocat",
			"3 springs avocat cheese",
			"3 springs concombre cheese",
			"Edamame",
			"Salade de chou"
		],
	},
	{
		title: "Plateau Salmon",
		piecesNumber: 24,
		image: "/plateau_salmon.png",
		price: 21.9,
		elements: [
			"6 californias saumon avocat",
			"6 makis salmon roll",
			"6 makis salmon",
			"6 springs saumon avocat",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Assortiment",
		piecesNumber: 18,
		image: "/plateau_assortiment.png",
		price: 17.5,
		elements: [
			"3 californias saumon avocat",
			"3 californias thon avocat", 
			"3 springs saumon avocat",
			"3 springs thon avocat",
			"6 makis salmon roll",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Royal",
		piecesNumber: 18,
		image: "/plateau_royal.png",
		price: 21.9,
		elements: [
			"3 californias saumon avocat",
			"3 springs saumon avocat",
			"2 sushis saumon", 
			"2 sushis thon",
			"2 sushis daurade",
			"1 sushi crevette",
			"1 sushi ikura",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Plateau Gourmand",
		piecesNumber: 20,
		image: "/plateau_gourmand.png",
		price: 23.9,
		elements: [
			"6 californias saumon avocat",
			"6 springs saumon avocat",
			"2 sushis saumon",
			"2 sushis thon",
			"2 sushis daurade",
			"1 sushi crevette",
			"1 sushi ikura",
			"Edamame",
			"Salade de chou",
		],
	},
	{
		title: "Box pour 2 ou 3",
		piecesNumber: 42,
		image: "/box_pour_2_v2.png",
		price: 44,
		elements: [
			"6 makis salmon roll",
			"6 makis saumon",
			"6 californias saumon avocat",
			"6 springs saumon avocat",
			"6 springs thon cuit avocat",
			"4 sushis saumon",
			"2 sushis thon",
			"3 sashimis saumon",
			"3 sashimis thon",
		],
	},
	{
		title: "Box Sushi Shokudo",
		piecesNumber: 46,
		image: "/box_sushi_shokudo.png",
		price: 55,
		elements: [
			"4 sushis saumon",
			"2 sushis thon",
			"2 tulips tartare saumon avocat",
			"6 makis salmon roll",
			"6 californias saumon avocat",
			"6 californias foie gras",
			"6 springs crevette avocat",
			"6 springs tataki saumon",
			"8 tazuna rolls salmon teriyaki",
		],
	},
];